server:
  port: 8080

spring:
  application:
    name: api-gateway

  logging:
    level:
      org.springframework.cloud.gateway: DEBUG

  cloud:
    gateway:
      server:
        webflux:
          routes:
            # -------------------- USER SERVICE ROUTES --------------------
            - id: user-service-swagger
              uri: https://user-service-ngah.onrender.com
              predicates:
                - Path=/api/user/v3/api-docs, /api/user/v3/api-docs/**
              filters:
                - StripPrefix=2

            - id: user-service-user-api
              uri: https://user-service-ngah.onrender.com
              predicates:
                - Path=/api/user/**
              filters:
                - StripPrefix=1

            - id: user-service-auth-api
              uri: https://user-service-ngah.onrender.com
              predicates:
                - Path=/api/authentication/**
              filters:
                - StripPrefix=1
            # -------------------- FORUM SERVICE ROUTES --------------------
            - id: forum-service-swagger
              uri: https://forumpost-service.onrender.com
              predicates:
                - Path=/api/forum/v3/api-docs, /api/forum/v3/api-docs/**
              filters:
                - StripPrefix=2

            - id: forum-post-comment-api
              uri: https://forumpost-service.onrender.com
              predicates:
                - Path=/api/comment/**
              filters:
                - StripPrefix=1

            - id: forum-post-forum-post-api
              uri: https://forumpost-service.onrender.com
              predicates:
                - Path=/api/forum-post/**
              filters:
                - StripPrefix=1

            - id: forum-post-post-interaction-api
              uri: https://forumpost-service.onrender.com
              predicates:
                - Path=/api/post-interaction/**
              filters:
                - StripPrefix=1

            - id: forum-post-share-api
              uri: https://forumpost-service.onrender.com
              predicates:
                - Path=/api/share/**
              filters:
                - StripPrefix=1

# -------------------- SPRING-DOC CONFIGURATION --------------------
springdoc:
  gateway:
    enabled: true
  swagger-ui:
    path: /swagger-ui/index.html
    urls:
      - name: user-service
        url: /api/user/v3/api-docs
      - name: forum-service
        url: /api/forum/v3/api-docs

jwt:
  secret: "ZhA/MMY/9vj95sgNMUnQIG/VDOCywzYVcf+R+HEhokc="
